version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "weekly"

update:
  - package-ecosystem: "pub"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "weekly"
